version: "3"
services:
  hmi-ws:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    image: siliconlife/hmi-ws
    hostname: hmi-ws
    restart: unless-stopped
    container_name: hmi-ws
    ports:
      - "6030:6030"
    environment:
      PORT: 6030
      MONGO_URL: ""
      MONGO_DB: "eyeflow"
      PACKAGE_ID: ""
      DATA_PATH: "/opt/eyeflow/data"
      JWT_PRIVATE_KEY_FILE: "/usr/src/app/keys/jwtRS256.key"
      JWT_PUBLIC_KEY_FILE: "/usr/src/app/keys/jwtRS256.key.pub"
      USER_DEFAULT_PASSWORD: "123456"
    volumes:
      - /opt/eyeflow/data:/opt/eyeflow/data
      - /opt/eyeflow/log:/usr/src/app/logs