version: "3"
services:
  hmi-ws:
    build:
      context: .
      dockerfile: Dockerfile
    image: siliconlife/hmi-ws
    hostname: hmi-ws
    network_mode: host
    restart: always
    container_name: hmi-ws
    environment:
      PORT: 6030
      MONGO_URL: ""
      MONGO_DB: "eyeflow"
      PACKAGE_ID: ""
      DATA_PATH: "/data"
    volumes:
      - /opt/eyeflow/data/:/data
      - /opt/eyeflow/log/:/usr/src/app/logs
      - /mnt:/edges